//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQeuryCracking.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cityidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string citynameField;
        
        private int citystudentidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cityid {
            get {
                return this.cityidField;
            }
            set {
                if ((this.cityidField.Equals(value) != true)) {
                    this.cityidField = value;
                    this.RaisePropertyChanged("cityid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cityname {
            get {
                return this.citynameField;
            }
            set {
                if ((object.ReferenceEquals(this.citynameField, value) != true)) {
                    this.citynameField = value;
                    this.RaisePropertyChanged("cityname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int citystudentid {
            get {
                return this.citystudentidField;
            }
            set {
                if ((this.citystudentidField.Equals(value) != true)) {
                    this.citystudentidField = value;
                    this.RaisePropertyChanged("citystudentid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name getCityIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityId", ReplyAction="*")]
        jQeuryCracking.ServiceReference1.getCityIdResponse getCityId(jQeuryCracking.ServiceReference1.getCityIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityId", ReplyAction="*")]
        System.Threading.Tasks.Task<jQeuryCracking.ServiceReference1.getCityIdResponse> getCityIdAsync(jQeuryCracking.ServiceReference1.getCityIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityId", Namespace="http://tempuri.org/", Order=0)]
        public jQeuryCracking.ServiceReference1.getCityIdRequestBody Body;
        
        public getCityIdRequest() {
        }
        
        public getCityIdRequest(jQeuryCracking.ServiceReference1.getCityIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cityid;
        
        public getCityIdRequestBody() {
        }
        
        public getCityIdRequestBody(int cityid) {
            this.cityid = cityid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public jQeuryCracking.ServiceReference1.getCityIdResponseBody Body;
        
        public getCityIdResponse() {
        }
        
        public getCityIdResponse(jQeuryCracking.ServiceReference1.getCityIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public jQeuryCracking.ServiceReference1.Employee getCityIdResult;
        
        public getCityIdResponseBody() {
        }
        
        public getCityIdResponseBody(jQeuryCracking.ServiceReference1.Employee getCityIdResult) {
            this.getCityIdResult = getCityIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : jQeuryCracking.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<jQeuryCracking.ServiceReference1.WebService1Soap>, jQeuryCracking.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        jQeuryCracking.ServiceReference1.getCityIdResponse jQeuryCracking.ServiceReference1.WebService1Soap.getCityId(jQeuryCracking.ServiceReference1.getCityIdRequest request) {
            return base.Channel.getCityId(request);
        }
        
        public jQeuryCracking.ServiceReference1.Employee getCityId(int cityid) {
            jQeuryCracking.ServiceReference1.getCityIdRequest inValue = new jQeuryCracking.ServiceReference1.getCityIdRequest();
            inValue.Body = new jQeuryCracking.ServiceReference1.getCityIdRequestBody();
            inValue.Body.cityid = cityid;
            jQeuryCracking.ServiceReference1.getCityIdResponse retVal = ((jQeuryCracking.ServiceReference1.WebService1Soap)(this)).getCityId(inValue);
            return retVal.Body.getCityIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<jQeuryCracking.ServiceReference1.getCityIdResponse> jQeuryCracking.ServiceReference1.WebService1Soap.getCityIdAsync(jQeuryCracking.ServiceReference1.getCityIdRequest request) {
            return base.Channel.getCityIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<jQeuryCracking.ServiceReference1.getCityIdResponse> getCityIdAsync(int cityid) {
            jQeuryCracking.ServiceReference1.getCityIdRequest inValue = new jQeuryCracking.ServiceReference1.getCityIdRequest();
            inValue.Body = new jQeuryCracking.ServiceReference1.getCityIdRequestBody();
            inValue.Body.cityid = cityid;
            return ((jQeuryCracking.ServiceReference1.WebService1Soap)(this)).getCityIdAsync(inValue);
        }
    }
}
